/**
 * Le catalogue des spécialités juridiques.
 *
 * Chaque entrée décrit UN spécialiste : ce qu'il traite, ce qu'il ne traite
 * pas, les textes sur lesquels il s'appuie, et les délais qu'il doit signaler.
 * Ce fichier est du contenu, pas du code : il ne fait aucun appel réseau, ne
 * dépend de rien, et se lit comme une fiche. C'est délibéré — il est la seule
 * source de vérité pour trois choses à la fois : l'aiguillage automatique
 * (`lib/aiguillage.ts`), la consigne donnée au modèle (`lib/juriste.ts`) et ce
 * que le visiteur lit à l'écran. Faire diverger ces trois-là serait le moyen le
 * plus sûr d'avoir un spécialiste qui affiche un périmètre et en applique un
 * autre.
 *
 * ── Sur les références ──────────────────────────────────────────────────────
 * `sources` ne contient que des NOMS de textes, jamais de numéros d'article.
 * Un numéro d'article change (recodifications, réformes) et une référence
 * périmée citée devant un juge coûte plus cher que pas de référence du tout.
 * Le modèle reçoit la même consigne : nommer le texte, jamais le numéroter.
 *
 * ── Sur les délais ──────────────────────────────────────────────────────────
 * `delais` est le champ qui justifie à lui seul l'existence de ce fichier. En
 * droit, la faute qu'on ne rattrape pas n'est presque jamais d'avoir mal
 * argumenté : c'est d'avoir laissé passer un délai. Ils sont donc affichés en
 * clair sur la page du spécialiste, avant même la première question, et
 * rappelés au modèle à chaque réponse.
 *
 * Ils sont écrits au 5 septembre 2026 et doivent être revus quand la loi
 * bouge. Aucun n'est présenté comme s'appliquant automatiquement : la règle
 * affichée partout est que la mention des voies de recours portée sur la
 * décision elle-même l'emporte sur ce que dit cette page.
 */

export type DomaineId =
  | 'travail'
  | 'immobilier'
  | 'famille'
  | 'consommation'
  | 'succession'
  | 'social'
  | 'penal'
  | 'administratif'
  | 'etrangers'
  | 'affaires'
  | 'fiscal'
  | 'routier'
  | 'numerique';

export interface Renvoi {
  /** La situation qui sort du périmètre, telle qu'un visiteur la formulerait. */
  quand: string;
  vers: DomaineId;
}

export interface Domaine {
  id: DomaineId;
  /** Nom du spécialiste, tel qu'il s'affiche sur sa carte et dans le fil. */
  label: string;
  /** Une ligne sous le titre : de quoi il s'occupe, en langue de tous les jours. */
  resume: string;
  /** Les matières couvertes. Affichées, et données au modèle comme périmètre. */
  matieres: string[];
  /** Ce qui n'est pas de son ressort, et à qui passer la main. */
  renvois: Renvoi[];
  /** Textes de référence, nommés sans numéro d'article (voir l'en-tête). */
  sources: string[];
  /** Délais couperets. Le premier de la liste est le plus souvent décisif. */
  delais: string[];
  /**
   * Termes décisifs pour l'aiguillage : leur présence désigne le domaine à
   * elle seule. « prud'hommes » ne veut rien dire d'autre que le travail.
   */
  signaux: string[];
  /**
   * Champ lexical : chacun pèse peu, mais leur accumulation compte. Ils
   * peuvent être partagés entre domaines — « contrat » est partout.
   */
  motsCles: string[];
  /** Questions d'exemple, cliquables. Elles montrent le niveau de précision utile. */
  exemples: string[];
}

/**
 * L'ordre de cette liste est celui de la grille d'accueil, et il est trié par
 * fréquence des besoins, pas par ordre alphabétique : le logement et le
 * travail sont ce pour quoi on vient.
 */
export const DOMAINES: Domaine[] = [
  {
    id: 'immobilier',
    label: 'Logement et immobilier',
    resume: 'Location, copropriété, achat, voisinage, travaux.',
    matieres: [
      'bail d’habitation vide ou meublé : loyer, charges, préavis, congé',
      'dépôt de garantie, état des lieux, réparations locatives',
      'logement indécent ou insalubre, impayés de loyer, expulsion',
      'copropriété : assemblée générale, charges, syndic, travaux',
      'achat et vente : compromis, condition suspensive, vices cachés',
      'troubles de voisinage, mitoyenneté, servitudes',
    ],
    renvois: [
      { quand: 'un permis de construire ou une décision de la mairie', vers: 'administratif' },
      { quand: 'un local commercial ou professionnel', vers: 'affaires' },
      { quand: 'un bien reçu en héritage ou en indivision successorale', vers: 'succession' },
      { quand: 'la taxe foncière ou la plus-value immobilière', vers: 'fiscal' },
    ],
    sources: [
      'la loi du 6 juillet 1989 sur les rapports locatifs',
      'la loi du 10 juillet 1965 sur la copropriété',
      'le code civil (louage, vente, propriété)',
      'le code de la construction et de l’habitation',
    ],
    delais: [
      'Contester une décision d’assemblée générale de copropriété : deux mois à compter de la notification du procès-verbal, et ce délai est très strictement appliqué.',
      'Restitution du dépôt de garantie : un mois après la remise des clés si l’état des lieux de sortie est conforme à celui d’entrée, deux mois sinon.',
      'Congé donné par le bailleur : six mois avant l’échéance pour un logement vide, trois mois pour un meublé — un congé tardif ne vaut rien.',
      'Vice caché : deux ans à compter de sa découverte pour agir contre le vendeur.',
      'Achat d’un logement : dix jours de rétractation à compter de la notification du compromis signé.',
    ],
    signaux: [
      'bail',
      'loyer',
      'locataire',
      'bailleur',
      'proprietaire',
      'copropriete',
      'syndic',
      'preavis',
      'depot de garantie',
      'etat des lieux',
      'expulsion',
      'colocation',
      'meuble',
      'quittance',
      'charges locatives',
      'assemblee generale',
      'vice cache',
      'compromis',
      'voisinage',
      'servitude',
      'mitoyennete',
      'insalubre',
      'indecent',
      'preemption',
      'sci',
    ],
    motsCles: [
      'logement',
      'appartement',
      'maison',
      'immeuble',
      'louer',
      'location',
      'demenagement',
      'travaux',
      'humidite',
      'moisissure',
      'chauffage',
      'ascenseur',
      'parties communes',
      'voisin',
      'bruit',
      'cloture',
      'terrain',
      'notaire',
      'achat',
      'vente',
      'agence immobiliere',
      'diagnostic',
    ],
    exemples: [
      'Mon propriétaire refuse de me rendre le dépôt de garantie, deux mois après mon départ.',
      'Le syndic a fait voter des travaux que je conteste : quel recours et dans quel délai ?',
      'J’ai découvert une infiltration trois mois après l’achat de ma maison.',
      'Puis-je donner un préavis d’un mois pour mon appartement à Lyon ?',
    ],
  },
  {
    id: 'travail',
    label: 'Travail et emploi',
    resume: 'Contrat, licenciement, salaire, harcèlement, rupture.',
    matieres: [
      'contrat de travail : CDI, CDD, période d’essai, clauses',
      'licenciement, rupture conventionnelle, démission, prise d’acte',
      'salaire, heures supplémentaires, primes, solde de tout compte',
      'congés payés, arrêt maladie, temps de travail',
      'harcèlement moral ou sexuel, discrimination, inaptitude',
      'saisine du conseil de prud’hommes',
    ],
    renvois: [
      { quand: 'des indemnités chômage, une pension ou la sécurité sociale', vers: 'social' },
      { quand: 'un agent public, un fonctionnaire ou un contractuel de la fonction publique', vers: 'administratif' },
      { quand: 'un dirigeant sans contrat de travail, ou une société en difficulté', vers: 'affaires' },
      { quand: 'des violences ou un vol commis au travail', vers: 'penal' },
    ],
    sources: [
      'le code du travail',
      'la convention collective applicable à l’entreprise',
      'l’accord d’entreprise et le règlement intérieur',
      'la jurisprudence de la chambre sociale de la Cour de cassation',
    ],
    delais: [
      'Contester un licenciement devant le conseil de prud’hommes : douze mois à compter de la notification de la lettre.',
      'Réclamer des salaires impayés ou des heures supplémentaires : trois ans en arrière.',
      'Rupture conventionnelle : quinze jours calendaires pour se rétracter après la signature, puis douze mois pour la contester.',
      'Dénoncer un reçu pour solde de tout compte signé : six mois — passé ce délai, il devient libératoire pour les sommes qui y figurent.',
      'Contester une sanction disciplinaire : deux mois pour l’employeur pour sanctionner un fait connu.',
    ],
    signaux: [
      'licenciement',
      'prud',
      'prudhommes',
      'employeur',
      'salarie',
      'cdd',
      'cdi',
      'rupture conventionnelle',
      'periode d essai',
      'solde de tout compte',
      'heures supplementaires',
      'convention collective',
      'preavis de demission',
      'demission',
      'inaptitude',
      'faute grave',
      'harcelement moral',
      'clause de non concurrence',
      'mise a pied',
      'entretien prealable',
      'medecine du travail',
      'comite social',
      'greve',
      'temps partiel',
    ],
    motsCles: [
      'travail',
      'emploi',
      'salaire',
      'contrat',
      'patron',
      'entreprise',
      'bulletin de paie',
      'fiche de paie',
      'prime',
      'conges',
      'rtt',
      'arret maladie',
      'accident du travail',
      'syndicat',
      'teletravail',
      'mutation',
      'promotion',
      'stage',
      'alternance',
      'interim',
    ],
    exemples: [
      'J’ai été licencié pour faute grave, mais je n’ai jamais eu d’entretien préalable.',
      'Mon employeur ne paie pas mes heures supplémentaires depuis un an.',
      'Puis-je refuser une rupture conventionnelle et quelles sont les conséquences ?',
      'Que faire face à un harcèlement moral de mon supérieur ?',
    ],
  },
  {
    id: 'famille',
    label: 'Famille et couple',
    resume: 'Divorce, enfants, pension, filiation, protection.',
    matieres: [
      'divorce et séparation : procédure, torts, prestation compensatoire',
      'PACS, concubinage, régimes matrimoniaux',
      'autorité parentale, résidence des enfants, droit de visite',
      'pension alimentaire : fixation, révision, non-paiement',
      'filiation, adoption, reconnaissance',
      'violences conjugales et ordonnance de protection',
      'tutelle, curatelle, habilitation familiale',
    ],
    renvois: [
      { quand: 'une succession, un testament ou un héritage', vers: 'succession' },
      { quand: 'des violences à faire juger et sanctionner', vers: 'penal' },
      { quand: 'des allocations familiales ou la CAF', vers: 'social' },
      { quand: 'le titre de séjour d’un conjoint étranger', vers: 'etrangers' },
    ],
    sources: [
      'le code civil (mariage, divorce, autorité parentale, filiation)',
      'le code de procédure civile',
      'la jurisprudence de la première chambre civile de la Cour de cassation',
    ],
    delais: [
      'Faire appel d’un jugement du juge aux affaires familiales : un mois à compter de la signification par huissier — c’est la signification qui déclenche le délai, pas la date du jugement.',
      'Ordonnance de protection en cas de violences : le juge statue sous six jours à compter de la fixation de l’audience, la demande peut être faite sans attendre un dépôt de plainte.',
      'Contester une filiation établie : les délais varient de cinq à dix ans selon la situation, et se comptent parfois depuis la naissance.',
      'Non-paiement d’une pension alimentaire : deux mois d’impayés suffisent à saisir directement l’organisme de recouvrement, sans attendre.',
    ],
    signaux: [
      'divorce',
      'pension alimentaire',
      'garde des enfants',
      'autorite parentale',
      'droit de visite',
      'pacs',
      'concubinage',
      'prestation compensatoire',
      'juge aux affaires familiales',
      'jaf',
      'filiation',
      'adoption',
      'tutelle',
      'curatelle',
      'ordonnance de protection',
      'violences conjugales',
      'residence alternee',
      'contribution a l entretien',
      'mariage',
      'regime matrimonial',
      'communaute reduite',
      'separation de biens',
    ],
    motsCles: [
      'famille',
      'couple',
      'epoux',
      'epouse',
      'conjoint',
      'enfant',
      'parent',
      'pere',
      'mere',
      'separation',
      'seul parent',
      'nom de famille',
      'majeur protege',
      'grand parent',
    ],
    exemples: [
      'Mon ex-conjoint ne paie plus la pension alimentaire depuis six mois.',
      'Comment demander une résidence alternée pour mes enfants ?',
      'Quelle procédure de divorce si nous sommes d’accord sur tout ?',
      'Je subis des violences : comment obtenir une ordonnance de protection ?',
    ],
  },
  {
    id: 'consommation',
    label: 'Consommation et achats',
    resume: 'Garanties, livraisons, abonnements, crédit, arnaques.',
    matieres: [
      'garantie légale de conformité et vices cachés sur un achat',
      'achat en ligne, rétractation, livraison non conforme ou jamais arrivée',
      'démarchage à domicile ou téléphonique, contrat signé sous pression',
      'abonnements, résiliation, prélèvements non autorisés',
      'crédit à la consommation, surendettement',
      'litige avec un artisan, un garagiste, une compagnie aérienne',
      'banque et assurance : frais, refus d’indemnisation',
    ],
    renvois: [
      { quand: 'un achat immobilier ou des travaux dans un logement loué', vers: 'immobilier' },
      { quand: 'une escroquerie caractérisée à faire poursuivre', vers: 'penal' },
      { quand: 'un litige entre deux professionnels', vers: 'affaires' },
      { quand: 'des données personnelles utilisées sans accord', vers: 'numerique' },
    ],
    sources: [
      'le code de la consommation',
      'le code civil (vente, vices cachés, responsabilité contractuelle)',
      'le code des assurances',
      'le code monétaire et financier',
    ],
    delais: [
      'Rétractation d’un achat à distance ou d’un démarchage : quatorze jours à compter de la réception du bien ou de la signature du contrat.',
      'Garantie légale de conformité : deux ans à compter de la livraison pour un bien neuf, un an pour un bien d’occasion — et pendant les deux premières années, c’est au vendeur de prouver que le défaut n’existait pas.',
      'Vice caché : deux ans à compter de la découverte du défaut.',
      'Crédit à la consommation : quatorze jours pour se rétracter à compter de l’acceptation de l’offre.',
      'Retard ou annulation d’un vol : la réclamation reste possible pendant cinq ans, mais les preuves (cartes d’embarquement, courriels) se perdent bien avant.',
    ],
    signaux: [
      'garantie',
      'retractation',
      'remboursement',
      'sav',
      'livraison',
      'colis',
      'abonnement',
      'resiliation',
      'prelevement',
      'demarchage',
      'demarcheur',
      'arnaque',
      'litige commercial',
      'vendeur',
      'commande',
      'credit a la consommation',
      'surendettement',
      'garagiste',
      'artisan',
      'devis',
      'assurance',
      'mediateur de la consommation',
      'clause abusive',
    ],
    motsCles: [
      'achat',
      'acheter',
      'produit',
      'defectueux',
      'panne',
      'facture',
      'boutique',
      'magasin',
      'site internet',
      'commercant',
      'banque',
      'compte bancaire',
      'frais',
      'telephone',
      'internet',
      'voyage',
      'vol',
      'billet',
      'reservation',
    ],
    exemples: [
      'Mon lave-linge est tombé en panne après quinze mois : que puis-je exiger ?',
      'Un démarcheur m’a fait signer un contrat de panneaux solaires, je veux annuler.',
      'Le vendeur refuse de me rembourser un colis jamais livré.',
      'Ma banque me prélève des frais que je n’ai jamais acceptés.',
    ],
  },
  {
    id: 'social',
    label: 'Protection sociale',
    resume: 'Sécurité sociale, chômage, retraite, handicap, aides.',
    matieres: [
      'assurance maladie : remboursements, arrêts de travail, invalidité',
      'accident du travail et maladie professionnelle',
      'allocations chômage : refus, radiation, trop-perçu',
      'retraite : liquidation, trimestres, pension de réversion',
      'CAF : RSA, APL, prime d’activité, allocations familiales',
      'handicap : MDPH, AAH, reconnaissance de travailleur handicapé',
      'contestation d’une décision d’un organisme social',
    ],
    renvois: [
      { quand: 'un litige avec l’employeur lui-même', vers: 'travail' },
      { quand: 'une décision d’une administration hors organismes sociaux', vers: 'administratif' },
      { quand: 'une fraude reprochée avec des poursuites pénales', vers: 'penal' },
    ],
    sources: [
      'le code de la sécurité sociale',
      'le code de l’action sociale et des familles',
      'le règlement d’assurance chômage',
      'le code du travail pour les accidents du travail',
    ],
    delais: [
      'Contester une décision de la CPAM, de la CAF ou de la MSA : deux mois pour saisir la commission de recours amiable — ce recours préalable est obligatoire avant tout juge.',
      'Contester une décision de France Travail : deux mois, après une médiation possible.',
      'Déclarer un accident du travail : vingt-quatre heures pour prévenir l’employeur, quarante-huit heures pour l’employeur pour le déclarer à la caisse.',
      'Recours contre une décision de la MDPH : deux mois, par recours administratif préalable obligatoire.',
    ],
    signaux: [
      'cpam',
      'securite sociale',
      'assurance maladie',
      'caf',
      'rsa',
      'apl',
      'prime d activite',
      'allocation',
      'france travail',
      'pole emploi',
      'chomage',
      'are',
      'radiation',
      'trop percu',
      'retraite',
      'pension de reversion',
      'trimestres',
      'carsat',
      'mdph',
      'aah',
      'invalidite',
      'maladie professionnelle',
      'commission de recours amiable',
      'msa',
      'indemnites journalieres',
    ],
    motsCles: [
      'aide',
      'aides',
      'prestation',
      'dossier',
      'organisme',
      'remboursement',
      'mutuelle',
      'medecin',
      'hopital',
      'arret',
      'handicap',
      'cotisations',
      'affiliation',
    ],
    exemples: [
      'La CAF me réclame un trop-perçu de 4 000 € que je conteste.',
      'Mon arrêt de travail n’est plus indemnisé, sans explication.',
      'France Travail m’a radié : quel recours et sous quel délai ?',
      'Comment contester le refus de reconnaissance de ma maladie professionnelle ?',
    ],
  },
  {
    id: 'penal',
    label: 'Pénal et victimes',
    resume: 'Plainte, garde à vue, convocation, indemnisation.',
    matieres: [
      'porter plainte, main courante, classement sans suite',
      'être victime : constitution de partie civile, indemnisation',
      'garde à vue, convocation au commissariat, droits de la défense',
      'infractions courantes : vol, violences, menaces, escroquerie',
      'procédure : comparution, ordonnance pénale, appel',
      'casier judiciaire et effacement',
    ],
    renvois: [
      { quand: 'une infraction routière, un permis ou une amende', vers: 'routier' },
      { quand: 'des propos ou contenus en ligne, cyberharcèlement', vers: 'numerique' },
      { quand: 'un divorce ou la garde des enfants après des violences', vers: 'famille' },
    ],
    sources: [
      'le code pénal',
      'le code de procédure pénale',
      'la loi du 29 juillet 1881 sur la liberté de la presse pour la diffamation et l’injure',
    ],
    delais: [
      'Prescription de l’action publique : un an pour une contravention, six ans pour un délit, vingt ans pour un crime — avec des règles particulières pour les infractions commises sur des mineurs.',
      'Diffamation et injure : trois mois seulement à compter de la publication. C’est le délai le plus court du droit français, et il est fatal.',
      'Faire appel d’un jugement correctionnel : dix jours à compter du prononcé ou de la signification.',
      'Contester un classement sans suite : la plainte avec constitution de partie civile devant le juge d’instruction est possible trois mois après le dépôt de la plainte simple restée sans réponse.',
    ],
    signaux: [
      'plainte',
      'garde a vue',
      'commissariat',
      'gendarmerie',
      'procureur',
      'classement sans suite',
      'partie civile',
      'tribunal correctionnel',
      'casier judiciaire',
      'vol',
      'agression',
      'violences',
      'menaces',
      'escroquerie',
      'abus de confiance',
      'stupefiants',
      'convocation',
      'sursis',
      'juge d instruction',
      'avocat commis d office',
      'main courante',
      'diffamation',
      'injure',
      'harcelement',
    ],
    motsCles: [
      'police',
      'justice',
      'proces',
      'audience',
      'condamnation',
      'peine',
      'amende penale',
      'prison',
      'victime',
      'temoin',
      'prejudice',
      'dommages et interets',
      'infraction',
      'delit',
    ],
    exemples: [
      'Ma plainte pour escroquerie a été classée sans suite : que puis-je faire ?',
      'Je suis convoqué au commissariat comme mis en cause : quels sont mes droits ?',
      'Comment me constituer partie civile pour être indemnisé ?',
      'Un voisin me menace régulièrement : plainte ou main courante ?',
    ],
  },
  {
    id: 'administratif',
    label: 'Administration et urbanisme',
    resume: 'Mairie, préfecture, permis, fonction publique, recours.',
    matieres: [
      'contester une décision administrative : recours gracieux, recours contentieux',
      'urbanisme : permis de construire, déclaration de travaux, contestation par un tiers',
      'fonction publique : carrière, sanction, non-titulaires',
      'services publics : école, hôpital public, eau, voirie',
      'expropriation, domaine public, marchés publics',
      'référé-suspension et référé-liberté en cas d’urgence',
    ],
    renvois: [
      { quand: 'un titre de séjour, un visa ou une OQTF', vers: 'etrangers' },
      { quand: 'un impôt, une taxe ou un contrôle fiscal', vers: 'fiscal' },
      { quand: 'la CAF, la CPAM, France Travail ou la MDPH', vers: 'social' },
      { quand: 'un litige entre voisins sans intervention de la mairie', vers: 'immobilier' },
    ],
    sources: [
      'le code des relations entre le public et l’administration',
      'le code de justice administrative',
      'le code de l’urbanisme',
      'le code général de la fonction publique',
    ],
    delais: [
      'Recours contentieux devant le tribunal administratif : deux mois à compter de la notification ou de l’affichage de la décision. Ce délai est le socle du droit administratif et il ne pardonne pas.',
      'Un recours gracieux ou hiérarchique formé dans ces deux mois proroge le délai : le compteur repart à la réponse, ou au silence gardé pendant deux mois.',
      'Recours des tiers contre un permis de construire : deux mois à compter du premier jour de l’affichage régulier du panneau sur le terrain.',
      'Silence de l’administration pendant deux mois : il vaut acceptation dans de nombreux cas, mais rejet dans beaucoup d’autres — la règle applicable dépend de la procédure.',
    ],
    signaux: [
      'tribunal administratif',
      'recours gracieux',
      'recours hierarchique',
      'mairie',
      'permis de construire',
      'declaration prealable',
      'urbanisme',
      'plu',
      'fonction publique',
      'fonctionnaire',
      'agent public',
      'arrete municipal',
      'expropriation',
      'domaine public',
      'marche public',
      'refere suspension',
      'refere liberte',
      'commune',
      'conseil d etat',
      'voirie',
      'cadastre',
    ],
    motsCles: [
      'administration',
      'prefecture',
      'decision',
      'refus',
      'dossier',
      'demande',
      'service public',
      'ecole',
      'hopital',
      'travaux publics',
      'construction',
      'terrain',
      'autorisation',
      'agent',
      'concours',
    ],
    exemples: [
      'La mairie a refusé mon permis de construire : comment le contester ?',
      'Mon voisin construit une extension, le permis me semble illégal.',
      'Je suis agent territorial et je conteste une sanction disciplinaire.',
      'La préfecture ne répond pas à ma demande depuis quatre mois.',
    ],
  },
  {
    id: 'etrangers',
    label: 'Droit des étrangers',
    resume: 'Titre de séjour, visa, OQTF, naturalisation, asile.',
    matieres: [
      'première demande et renouvellement d’un titre de séjour',
      'refus de séjour, obligation de quitter le territoire (OQTF), rétention',
      'visas, regroupement familial, conjoint de Français',
      'naturalisation et déclaration de nationalité',
      'demande d’asile, protection subsidiaire, recours devant la CNDA',
      'droit au travail, changement de statut étudiant-salarié',
    ],
    renvois: [
      { quand: 'un mariage, un divorce ou la filiation en eux-mêmes', vers: 'famille' },
      { quand: 'un litige avec un employeur, même sans papiers', vers: 'travail' },
      { quand: 'une autre décision de préfecture sans lien avec le séjour', vers: 'administratif' },
    ],
    sources: [
      'le code de l’entrée et du séjour des étrangers et du droit d’asile (CESEDA)',
      'le code civil pour la nationalité',
      'les accords bilatéraux applicables selon le pays d’origine',
    ],
    delais: [
      'Recours contre une OQTF : le délai est très court et varie selon la décision — quarante-huit heures, sept jours, quinze jours ou trente jours. La mention des voies de recours portée sur l’arrêté lui-même fait foi : lisez-la avant toute chose, et comptez à partir de la remise en main propre ou de la notification.',
      'Recours devant la Cour nationale du droit d’asile après un rejet de l’OFPRA : un mois à compter de la notification.',
      'Refus de titre de séjour sans OQTF : deux mois pour saisir le tribunal administratif.',
      'Demande de renouvellement d’un titre : à déposer dans les deux à trois mois précédant l’expiration, sous peine de se retrouver en séjour irrégulier pendant l’instruction.',
    ],
    signaux: [
      'titre de sejour',
      'carte de sejour',
      'oqtf',
      'prefecture sejour',
      'visa',
      'naturalisation',
      'nationalite francaise',
      'asile',
      'ofpra',
      'cnda',
      'regroupement familial',
      'recepisse',
      'rendez vous prefecture',
      'sans papiers',
      'reconduite a la frontiere',
      'retention administrative',
      'passeport talent',
      'etudiant etranger',
      'changement de statut',
      'interdiction de retour',
      'ceseda',
    ],
    motsCles: [
      'etranger',
      'prefecture',
      'immigration',
      'sejour',
      'expulsion du territoire',
      'refugie',
      'apatride',
      'ressortissant',
      'pays d origine',
      'conjoint de francais',
      'vie privee et familiale',
      'traducteur',
      'consulat',
      'ambassade',
    ],
    exemples: [
      'J’ai reçu une OQTF avec un délai de trente jours : que dois-je faire en premier ?',
      'La préfecture refuse de renouveler mon titre salarié.',
      'Quelles conditions pour demander la naturalisation par décret ?',
      'Mon conjoint est français : quelle procédure pour un titre de séjour ?',
    ],
  },
  {
    id: 'succession',
    label: 'Successions et donations',
    resume: 'Héritage, testament, indivision, donation, partage.',
    matieres: [
      'ouverture d’une succession, options de l’héritier',
      'réserve héréditaire, quotité disponible, action en réduction',
      'testament : forme, contestation, exécution',
      'indivision entre héritiers, partage, vente d’un bien indivis',
      'donations, donation-partage, rapport à la succession',
      'assurance-vie et succession',
      'droits de succession et déclaration',
    ],
    renvois: [
      { quand: 'un divorce ou une pension alimentaire', vers: 'famille' },
      { quand: 'la gestion courante d’un bien loué', vers: 'immobilier' },
      { quand: 'le calcul ou la contestation des droits à payer', vers: 'fiscal' },
    ],
    sources: [
      'le code civil (successions, libéralités, indivision)',
      'le code général des impôts pour les droits de mutation',
      'la jurisprudence de la première chambre civile de la Cour de cassation',
    ],
    delais: [
      'Déclaration de succession auprès de l’administration fiscale : six mois à compter du décès en France, un an depuis l’étranger — l’intérêt de retard court ensuite.',
      'Option de l’héritier : quatre mois avant qu’un créancier ou un cohéritier puisse sommer de choisir, puis deux mois pour répondre. Le droit d’option s’éteint au bout de dix ans, et le silence vaut alors renonciation.',
      'Action en réduction d’une libéralité qui entame la réserve : cinq ans à compter de l’ouverture de la succession, ou deux ans à compter de la découverte de l’atteinte.',
      'Contester le partage : cinq ans, à compter du partage lui-même.',
    ],
    signaux: [
      'succession',
      'heritage',
      'herite',
      'heritier',
      'testament',
      'legs',
      'indivision',
      'partage',
      'donation',
      'reserve hereditaire',
      'quotite disponible',
      'usufruit',
      'nue propriete',
      'notaire succession',
      'assurance vie',
      'renonciation a succession',
      'deces',
      'defunt',
      'ayant droit',
      'droits de succession',
    ],
    motsCles: [
      'heriter',
      'transmettre',
      'patrimoine',
      'biens',
      'famille',
      'frere',
      'soeur',
      'parents',
      'enfants',
      'maison de famille',
      'compte bancaire du defunt',
      'inventaire',
    ],
    exemples: [
      'Mon frère occupe seul la maison de nos parents depuis le décès : que puis-je exiger ?',
      'Mon père a tout légué à un tiers : puis-je contester ?',
      'Comment sortir d’une indivision quand un héritier bloque la vente ?',
      'Une donation faite il y a quinze ans doit-elle être rapportée ?',
    ],
  },
  {
    id: 'affaires',
    label: 'Entreprise et commerce',
    resume: 'Société, bail commercial, impayés, contrats, difficultés.',
    matieres: [
      'création et statuts : SAS, SARL, micro-entreprise, association',
      'relations entre associés, cession de parts, dirigeant',
      'contrats commerciaux, conditions générales, rupture de relations',
      'impayés entre professionnels, injonction de payer, recouvrement',
      'bail commercial : renouvellement, déspécialisation, congé',
      'difficultés : mandat ad hoc, redressement, liquidation judiciaire',
      'concurrence déloyale, clientèle, fonds de commerce',
    ],
    renvois: [
      { quand: 'un salarié, un licenciement ou les prud’hommes', vers: 'travail' },
      { quand: 'un client particulier, non professionnel', vers: 'consommation' },
      { quand: 'la TVA, l’impôt sur les sociétés ou un contrôle', vers: 'fiscal' },
      { quand: 'un logement d’habitation', vers: 'immobilier' },
    ],
    sources: [
      'le code de commerce',
      'le code civil (contrats, responsabilité)',
      'le code monétaire et financier',
      'les statuts de la société eux-mêmes, qui priment sur les usages',
    ],
    delais: [
      'Déclarer une créance dans une procédure collective : deux mois à compter de la publication du jugement d’ouverture au BODACC. Une créance non déclarée devient inopposable — c’est le délai le plus coûteux du droit des affaires.',
      'Prescription entre commerçants et pour les actions commerciales : cinq ans.',
      'Bail commercial : le congé se donne six mois à l’avance pour la fin d’un trimestre civil ; la demande de renouvellement obéit à un formalisme strict.',
      'Contester une décision d’assemblée générale de société : trois ans en principe, mais les statuts et la nature du vice peuvent raccourcir ce délai.',
      'Cessation des paiements : le dirigeant doit déclarer dans les quarante-cinq jours, faute de quoi sa responsabilité personnelle peut être engagée.',
    ],
    signaux: [
      'sarl',
      'sas',
      'sasu',
      'eurl',
      'micro entreprise',
      'auto entrepreneur',
      'associe',
      'gerant',
      'president de societe',
      'statuts',
      'cession de parts',
      'fonds de commerce',
      'bail commercial',
      'kbis',
      'greffe',
      'tribunal de commerce',
      'liquidation judiciaire',
      'redressement judiciaire',
      'injonction de payer',
      'facture impayee',
      'client professionnel',
      'entre professionnels',
      'concurrence deloyale',
      'clause de non concurrence commerciale',
      'bodacc',
      'commissaire aux comptes',
    ],
    motsCles: [
      'entreprise',
      'societe',
      'commerce',
      'client',
      'fournisseur',
      'contrat commercial',
      'chiffre d affaires',
      'creation',
      'associes',
      'capital',
      'dirigeant',
      'faillite',
      'recouvrement',
      'prestataire',
      'sous traitance',
      'franchise',
    ],
    exemples: [
      'Un client professionnel ne paie pas ma facture depuis quatre mois.',
      'Mon associé bloque toutes les décisions : quelles sont mes options ?',
      'Mon bailleur commercial refuse le renouvellement du bail.',
      'SAS ou SARL pour une activité de conseil à deux associés ?',
    ],
  },
  {
    id: 'fiscal',
    label: 'Impôts et fiscalité',
    resume: 'Déclaration, contrôle, redressement, taxes locales.',
    matieres: [
      'impôt sur le revenu : déclaration, rectification, quotient familial',
      'contrôle fiscal, proposition de rectification, redressement',
      'taxe foncière, taxe d’habitation sur résidence secondaire',
      'plus-values immobilières et mobilières',
      'TVA et fiscalité de l’entreprise',
      'droits de donation et de succession',
      'recours : réclamation contentieuse, remise gracieuse, sursis de paiement',
    ],
    renvois: [
      { quand: 'la répartition d’un héritage entre héritiers', vers: 'succession' },
      { quand: 'la vie de la société elle-même, hors impôt', vers: 'affaires' },
      { quand: 'une autre décision administrative', vers: 'administratif' },
    ],
    sources: [
      'le code général des impôts',
      'le livre des procédures fiscales',
      'la doctrine administrative publiée au BOFiP, opposable à l’administration',
    ],
    delais: [
      'Réclamation contentieuse : jusqu’au 31 décembre de la deuxième année suivant celle de la mise en recouvrement ou du versement de l’impôt.',
      'Répondre à une proposition de rectification : trente jours, prorogeables trente jours de plus sur demande. Le silence vaut acceptation du redressement.',
      'Droit de reprise de l’administration : en principe trois ans pour l’impôt sur le revenu, l’impôt sur les sociétés et la TVA, davantage en cas d’activité occulte.',
      'Le sursis de paiement doit être demandé dans la réclamation elle-même : demandé après, il ne suspend plus le recouvrement.',
    ],
    signaux: [
      'impot',
      'impots',
      'fisc',
      'controle fiscal',
      'redressement fiscal',
      'proposition de rectification',
      'taxe fonciere',
      'taxe d habitation',
      'plus value',
      'tva',
      'declaration de revenus',
      'avis d imposition',
      'prelevement a la source',
      'niche fiscale',
      'ifi',
      'bofip',
      'mise en demeure fiscale',
      'majoration',
      'penalites fiscales',
      'reclamation contentieuse',
      'sursis de paiement',
    ],
    motsCles: [
      'declaration',
      'revenus',
      'foyer fiscal',
      'abattement',
      'credit d impot',
      'reduction',
      'centre des finances publiques',
      'tresor public',
      'recouvrement',
      'payer',
      'exoneration',
      'residence principale',
    ],
    exemples: [
      'J’ai reçu une proposition de rectification : que dois-je répondre et dans quel délai ?',
      'Comment contester ma taxe foncière qui a doublé ?',
      'Ai-je droit à l’exonération de plus-value sur la vente de ma résidence principale ?',
      'J’ai oublié de déclarer un compte à l’étranger.',
    ],
  },
  {
    id: 'routier',
    label: 'Route et permis',
    resume: 'Amendes, points, suspension, accident, alcoolémie.',
    matieres: [
      'amendes et contestation : excès de vitesse, stationnement, feu rouge',
      'permis à points : retrait, invalidation, reconstitution',
      'suspension et annulation du permis, visite médicale',
      'alcoolémie, stupéfiants au volant, délit de fuite',
      'accident de la route : constat, indemnisation, loi Badinter',
      'assurance automobile, refus de garantie, véhicule non assuré',
    ],
    renvois: [
      { quand: 'une infraction non routière ou une convocation pénale plus large', vers: 'penal' },
      { quand: 'un litige avec un garagiste ou un vendeur de véhicule', vers: 'consommation' },
      { quand: 'un accident survenu pendant le travail', vers: 'travail' },
    ],
    sources: [
      'le code de la route',
      'le code pénal et le code de procédure pénale pour les délits routiers',
      'la loi du 5 juillet 1985 sur l’indemnisation des victimes d’accidents de la circulation',
    ],
    delais: [
      'Contester un avis de contravention : quarante-cinq jours à compter de son envoi, en respectant la forme exigée — une contestation hors forme est déclarée irrecevable sans être examinée.',
      'Le paiement de l’amende vaut reconnaissance de l’infraction et entraîne le retrait de points : payer d’abord et contester ensuite est impossible.',
      'Recours contre une décision de retrait de points (lettre 48SI) : deux mois devant le tribunal administratif.',
      'Déclarer un sinistre à l’assureur : cinq jours ouvrés en principe, deux jours en cas de vol.',
    ],
    signaux: [
      'permis de conduire',
      'points',
      'exces de vitesse',
      'radar',
      'contravention',
      'amende',
      'stationnement',
      'suspension de permis',
      'annulation de permis',
      'alcoolemie',
      'alcool au volant',
      'stupefiants au volant',
      'delit de fuite',
      'constat amiable',
      'accident de la route',
      'code de la route',
      '48si',
      'stage de recuperation',
      'immobilisation du vehicule',
      'assurance auto',
      'permis probatoire',
    ],
    motsCles: [
      'voiture',
      'vehicule',
      'conduire',
      'conducteur',
      'route',
      'circulation',
      'moto',
      'scooter',
      'garage',
      'carte grise',
      'controle technique',
      'expert automobile',
      'indemnisation',
    ],
    exemples: [
      'J’ai reçu un avis de contravention pour un excès de vitesse que je n’ai pas commis.',
      'Mon permis est invalidé pour solde de points nul : quel recours ?',
      'Comment contester la responsabilité retenue après un accident ?',
      'Que se passe-t-il après un contrôle d’alcoolémie positif ?',
    ],
  },
  {
    id: 'numerique',
    label: 'Numérique et données',
    resume: 'RGPD, réseaux sociaux, e-commerce, contenus, contrefaçon.',
    matieres: [
      'données personnelles : droit d’accès, effacement, plainte CNIL',
      'contenus en ligne : diffamation, cyberharcèlement, retrait',
      'droit à l’image et vie privée sur internet',
      'propriété intellectuelle : droit d’auteur, contrefaçon, marques',
      'commerce en ligne : mentions légales, CGV, obligations du vendeur',
      'contrats numériques : SaaS, hébergement, sous-traitance RGPD',
    ],
    renvois: [
      { quand: 'un achat en ligne mal exécuté, du point de vue de l’acheteur', vers: 'consommation' },
      { quand: 'une plainte à déposer et une procédure pénale à suivre', vers: 'penal' },
      { quand: 'des données personnelles traitées par un employeur sur ses salariés', vers: 'travail' },
    ],
    sources: [
      'le règlement général sur la protection des données (RGPD)',
      'la loi Informatique et Libertés',
      'le code de la propriété intellectuelle',
      'la loi pour la confiance dans l’économie numérique (LCEN)',
      'la loi du 29 juillet 1881 pour la diffamation et l’injure publiques',
    ],
    delais: [
      'Réponse à une demande d’accès ou d’effacement adressée à un responsable de traitement : un mois, prorogeable de deux mois pour les demandes complexes.',
      'Diffamation ou injure publique, y compris en ligne : trois mois à compter de la première publication. Ce délai très court est la première chose à vérifier.',
      'Notification d’une violation de données à la CNIL : soixante-douze heures pour le responsable de traitement.',
      'Contrefaçon : cinq ans à compter du jour où le titulaire a connu les faits.',
    ],
    signaux: [
      'rgpd',
      'donnees personnelles',
      'cnil',
      'droit a l oubli',
      'droit d acces',
      'cookies',
      'reseaux sociaux',
      'cyberharcelement',
      'droit a l image',
      'contrefacon',
      'droit d auteur',
      'marque deposee',
      'nom de domaine',
      'hebergeur',
      'moderation',
      'deepfake',
      'usurpation d identite',
      'avis en ligne',
      'referencement',
      'cgv',
      'mentions legales',
      'saas',
      'piratage',
      'fuite de donnees',
    ],
    motsCles: [
      'donnees',
      'effacement',
      'internet',
      'site web',
      'application',
      'plateforme',
      'compte',
      'publication',
      'photo',
      'video',
      'message',
      'email',
      'logiciel',
      'code source',
      'intelligence artificielle',
      'contenu',
      'suppression',
    ],
    exemples: [
      'Une photo de moi est publiée sans mon accord : comment la faire retirer ?',
      'Un ancien employeur refuse d’effacer mes données : quel recours devant la CNIL ?',
      'Un concurrent utilise mon nom de marque sur son site.',
      'Quelles mentions dois-je afficher sur ma boutique en ligne ?',
    ],
  },
];

const PAR_ID = new Map<DomaineId, Domaine>(DOMAINES.map((domaine) => [domaine.id, domaine]));

export function estDomaineId(value: unknown): value is DomaineId {
  return typeof value === 'string' && PAR_ID.has(value as DomaineId);
}

/** Lève si l'identifiant est inconnu : un domaine manquant est un bug, pas un cas. */
export function domaine(id: DomaineId): Domaine {
  const found = PAR_ID.get(id);
  if (!found) throw new Error(`Domaine inconnu : ${id}`);
  return found;
}

export function domaineOuNull(id: unknown): Domaine | null {
  return estDomaineId(id) ? domaine(id) : null;
}
